apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  selector:
    name: airflow
  type: NodePort
  ports:
  - name: foo # Actually, no port is needed.
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  labels:
    name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airflow
  template:
    metadata:
      labels:
        name: airflow
    spec:
      containers:
      - image: puckel/docker-airflow
        name: airflow