version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/WorldOfGames"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/WorldOfGames/jenkinsslave"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/WorldOfGames"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/WorldOfGames/jenkinsslave"
    schedule:
      interval: "weekly"
