trigger:
- main

variables:
  DOCKER_HUB_REPO: 'shaharco1804/score_flask'
  CONTAINER_NAME: 'score_flask'
  imageVersion: 'v$(Date:yyyyMMdd)'

jobs:
- job: BuildAndPush
  displayName: 'Build test and push image to Docker Hub'
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - task: Docker@2
    inputs:
      containerRegistry: 'docker'
      command: 'login'

  - script: |
      docker rm -f $CONTAINER_NAME || true
      docker rm -f selenium || true
    displayName: 'Clean stage'

  - task: Docker@2
    inputs:
      containerRegistry: 'docker'
      repository: '$(DOCKER_HUB_REPO)'
      command: 'build'
      Dockerfile: 'devops_expert/WorldOfGames//Dockerfile'
      buildContext: 'devops_expert/WorldOfGames/'
    displayName: 'Build stage'

  - task: Docker@2
    inputs:
      containerRegistry: 'docker'
      command: 'start'
      container: 'shaharco1804/selenium:latest'

  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Container Registry'
      dockerComposeFile: 'devops_expert/WorldOfGames/docker-compose.yml'
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'rm --all'
    displayName: 'Run compose'

  - script: |
      sleep 5 && pytest devops_expert/WorldOfGames/test.py
    displayName: 'Test stage'

  - task: Docker@2
    inputs:
      containerRegistry: 'docker'
      repository: '$(DOCKER_HUB_REPO)'
      command: 'push'
      tags: '$(imageVersion)'
    displayName: 'Finalize stage'

  - task: Docker@2
    inputs:
      containerRegistry: 'docker'
      command: 'logout'